### ISSUE TITLE
Build Reittiopas javascript bundle into Application

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/react-native-proto#14]
Make it so that application does not load Reittiopas from web, but from local file

**Comment by 0is1** [comment]
I created new branch https://github.com/HSLdevcom/react-native-proto/tree/local-reittiopas-bundle that includes now a test implementation for local html/js/css -files for iOS and Android.

**Comment by 0is1** [comment]
I might need some help related to this. 

So if I understand right there isn't "fully static" build option at the moment in https://github.com/HSLdevcom/digitransit-ui and what we basically need here is exactly that kind of version of reittiopas.fi.

**Comment by 0is1** [comment]
I've managed to get this to work with iOS (only thing that doesn't work is geolocation because `Access to geolocation was blocked over insecure connection to http://127.0.0.1:8080`) but there's still some issues with Android.

Digitransit doesn't have (at the moment) any "one liner" that can create working index.html-file with only desired  js/css because there should be for example 
* `window.state` that is created in server side on production (see: http://github.com/HSLdevcom/digitransit-ui/blob/31a95008c967989cd62256be2c7c83caf635bd9e/app/client.js#L44)
* and also `getScripts` (http://github.com/HSLdevcom/digitransit-ui/blob/31a95008c967989cd62256be2c7c83caf635bd9e/app/server.js#L190)

**Comment by 0is1** [comment]
Bundle is (almost) working now with Android also (implementation is ugly though). 
Biggest problem is with icons svg file (won't load).

**Comment by 0is1** [comment]
Latest implementation is loading reittiopas.zip from locahost on mount and unzipping it to `documentDirectory` from where the static server is then serving the files. See: https://github.com/HSLdevcom/react-native-proto/blob/local-reittiopas-bundle/app/components/Main.js

Repo doesn't include reittiopas.zip at the moment.
