### ISSUE TITLE
Combine News and Reittiopas into a single page

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/react-native-proto#7]
Reittiopas should remain as WebView, News should be loaded from GraphQL API. @tuukka can help with API.

**Comment by 0is1** [comment]
@samuliheljo @tuukka is there any documentation available about the GraphQL API that we want to use here?

**Comment by 0is1** [comment]
[dynamic-newsfeed branch](https://github.com/HSLdevcom/react-native-proto/tree/dynamic-newsfeed) uses now GraphQL API with static query. It doesn't return right data yet because there is some issues with the GraphQL server.

**Comment by 0is1** [comment]
There's an issue with Android when combining `WebView` (reittiopas.fi) in `ScrollView` with other views / data in it etc. because WebView is also "scrolling view" and the main ScrollView captures (touch) events most of the time. So it's almost impossible to move around the map and you can't scroll the WebView etc.

Similar issue https://github.com/facebook/react-native/issues/10723

It might be possible to do some kind of workaround: 
* http://stackoverflow.com/questions/13257990/android-webview-inside-scrollview-scrolls-only-scrollview
* https://github.com/airbnb/react-native-maps/pull/343
